name: ONT_amplicon
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - snakemake-minimal=7.25.0
  - pandas=1.5.3
  - seqkit=2.4.0
  - minimap2=2.24
  - samtools=1.16.1
  - prinseq=0.20.4
