samples: ["1000463191", "1000463386", "1000465755", "1000548083", "1000463192", "1000465563", "1000536513", "100045744501", "100045751801", "100045756501", "100045771201"]

primer_forward: "CCAGCACTGACAGCAGYNGARAYNGG"
primer_reverse: "TACTGGACCACCTGGNGGNAYRWACAT"

reference: "references/Enterovirus_all_without_primer.fasta"

# factor which defines the minimal depth (min_depth=mapped_reads/min_depth_factor)
# to set a variable threshold based on how many reads were mapped per sample, this accounts for variability in sequenced reads
# factor has to be an integer
min_depth_factor: 100
# define minimal depth to fall back when the min_depth calculated as described above is lower than this threshold
min_depth_reads: 10

# threshold for ambiguity codes
het_fract: 0.25

# threshold to filter consensus sequences with more than ns_max_p percentage of Ns
ns_max_p: 5
